### ISSUE TITLE
Enable cf push without .git

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw-buildpack#2]
When a project (like [mdw-demo](https://github.com/CenturyLinkCloud/mdw-demo) includes their .git directory in .cfignore, the get the stack trace below.  This needs analysis to figure out how we can handle this.  At the same time, we can tackle #1.
```
2017-12-08T11:50:25.01-0700 [App/0]      OUT MDW initialization...
2017-12-08T11:50:25.01-0700 [App/0]      OUT   deployPath: /home/vcap/app/.java-buildpack/tomcat/webapps/mdw/
2017-12-08T11:50:25.01-0700 [App/0]      OUT   contextPath: /mdw
2017-12-08T11:50:25.01-0700 [App/0]      OUT [(i)20171208.18:50:25.015 ~13] Initialize com.centurylink.mdw.app.ApplicationContext
2017-12-08T11:50:25.01-0700 [App/0]      OUT [(i)20171208.18:50:25.017 ~13] Naming Provider: com.centurylink.mdw.container.plugin.tomcat.TomcatNaming
2017-12-08T11:50:25.01-0700 [App/0]      OUT Using Property Manager: com.centurylink.mdw.config.PaaSPropertyManager
2017-12-08T11:50:25.02-0700 [App/0]      OUT [(i)20171208.18:50:25.027 ~13] Data Source Provider: com.centurylink.mdw.container.plugin.tomcat.TomcatDataSource
2017-12-08T11:50:25.03-0700 [App/0]      OUT [(i)20171208.18:50:25.029 ~13] JMS Provider: com.centurylink.mdw.container.plugin.activemq.ActiveMqJms
2017-12-08T11:50:25.03-0700 [App/0]      OUT [(i)20171208.18:50:25.033 ~13] Thread Pool Provider: com.centurylink.mdw.container.plugin.CommonThreadPool
2017-12-08T11:50:25.06-0700 [App/0]      ERR     SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2017-12-08T11:50:25.06-0700 [App/0]      ERR SLF4J: Defaulting to no-operation (NOP) logger implementation
2017-12-08T11:50:25.06-0700 [App/0]      ERR SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2017-12-08T11:50:25.19-0700 [App/0]      OUT [(i)20171208.18:50:25.196 ~13] Loading assets from path: assets
2017-12-08T11:50:25.19-0700 [App/0]      OUT [(s)20171208.18:50:25.196 ~13] **** WARNING: Git location . does not contain a repository.  Cloning: https://github.com/Cen
turyLinkCloud/mdw-demo.git
2017-12-08T11:50:25.21-0700 [App/0]      OUT [(s)20171208.18:50:25.216 ~13] Error during Git up-to-date check.
2017-12-08T11:50:25.21-0700 [App/0]      OUT org.eclipse.jgit.api.errors.JGitInternalException: Destination path "." already exists and is not an empty directory
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at org.eclipse.jgit.api.CloneCommand.verifyDirectories(CloneCommand.java:243)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:179)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.file.VersionControlGit.cloneNoCheckout(VersionControlGit.java:637)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.file.VersionControlGit.cloneNoCheckout(VersionControlGit.java:623)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.DataAccess.getAssetVersionControl(DataAccess.java:159)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.DataAccess.getVcsProcessLoader(DataAccess.java:112)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.DataAccess.getProcessLoader(DataAccess.java:66)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.DataAccess.getProcessLoader(DataAccess.java:74)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.cache.impl.PackageCache.load(PackageCache.java:72)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.cache.impl.PackageCache.getPackageList(PackageCache.java:60)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.cache.impl.PackageCache.getPackage(PackageCache.java:201)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.EmbeddedDataAccess.create(EmbeddedDataAccess.java:55)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.DatabaseAccess.checkAndStartEmbeddedDb(DatabaseAccess.java:185)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.DatabaseAccess.<init>(DatabaseAccess.java:142)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.hub.MdwMain.startup(MdwMain.java:76)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at com.centurylink.mdw.hub.StartupListener.contextInitialized(StartupListener.java:40)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
2017-12-08T11:50:25.21-0700 [App/0]      OUT    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
2017-12-08T11:50:25.22-0700 [App/0]      OUT    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
2017-12-08T11:50:25.22-0700 [App/0]      OUT    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
2017-12-08T11:50:25.22-0700 [App/0]      OUT    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:976)
2017-12-08T11:50:25.22-0700 [App/0]      OUT    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1853)
2017-12-08T11:50:25.22-0700 [App/0]      OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2017-12-08T11:50:25.22-0700 [App/0]      OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2017-12-08T11:50:25.22-0700 [App/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-12-08T11:50:25.22-0700 [App/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-12-08T11:50:25.22-0700 [App/0]      OUT    at java.lang.Thread.run(Thread.java:745)
```

**Comment by jbrojdeCTL** [comment]
I believe this was resolved by specifying a path other than "." for the property mdw.git.local.path

**Comment by donaldoakes** [comment]
This is a good workaround if you want to take your assets from Git and don't actually want to push from local.  The reason is that the buildpack is wired to push to ".".  If I `cf push` with these settings:
```
MDW_ASSET_LOCATION: './git/assets'
"mdw.git.local.path": "./git"
```
Then mdw clones into ./git and loads assets from ./git/assets.  This works, but meanwhile the assets I pushed are ignored.  Also there's an exception message (which doesn't seem to affect anything).  May need a fix in [mdw](https://github.com/CenturyLinkCloud/mdw).
```
2017-12-08T12:31:46.02-0700 [App/0]      OUT ** Please import the MDW base and hub packages
2017-12-08T12:31:46.02-0700 [App/0]      OUT ****************************************
2017-12-08T12:31:46.02-0700 [App/0]      OUT ** WARNING: Asset location ./git/assets does not exist.
2017-12-08T12:31:46.02-0700 [App/0]      OUT ******************************************
2017-12-08T12:31:46.05-0700 [App/0]      ERR     SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2017-12-08T12:31:46.05-0700 [App/0]      ERR SLF4J: Defaulting to no-operation (NOP) logger implementation
2017-12-08T12:31:46.05-0700 [App/0]      ERR SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2017-12-08T12:31:46.18-0700 [App/0]      OUT [(i)20171208.19:31:46.185 ~13] Loading assets from path: assets
2017-12-08T12:31:46.18-0700 [App/0]      OUT [(s)20171208.19:31:46.185 ~13] **** WARNING: Git location ./git does not contain a repository.  Cloning: https://github.com
/CenturyLinkCloud/mdw-demo.git
2017-12-08T12:31:57.97-0700 [App/0]      OUT [(i)20171208.19:31:57.975 ~13] Located configuration file: /home/vcap/app/.java-buildpack/tomcat/webapps/mdw/META-INF/mdw/s
pring/application-context.xml
2017-12-08T12:31:58.79-0700 [App/0]      ERR SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
2017-12-08T12:31:58.79-0700 [App/0]      ERR SLF4J: Defaulting to no-operation MDCAdapter implementation.
2017-12-08T12:31:58.79-0700 [App/0]      ERR SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
2017-12-08T12:31:59.96-0700 [App/0]      OUT [(s)20171208.19:31:59.962 ~13] Error during Git up-to-date check.
2017-12-08T12:31:59.96-0700 [App/0]      OUT com.centurylink.mdw.dataaccess.DataAccessException: Cannot create PoolableConnectionFactory (Could not connect to address=(
host=localhost)(port=3309)(type=master) : Connection refused)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.DataAccess.getAssetVersionControl(DataAccess.java:207)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.DataAccess.getVcsProcessLoader(DataAccess.java:112)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.DataAccess.getProcessLoader(DataAccess.java:66)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.DataAccess.getProcessLoader(DataAccess.java:74)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at com.centurylink.mdw.cache.impl.PackageCache.load(PackageCache.java:72)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at com.centurylink.mdw.cache.impl.PackageCache.getPackageList(PackageCache.java:60)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at com.centurylink.mdw.cache.impl.PackageCache.getPackage(PackageCache.java:201)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.EmbeddedDataAccess.create(EmbeddedDataAccess.java:55)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.DatabaseAccess.checkAndStartEmbeddedDb(DatabaseAccess.java:185)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1853)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at com.centurylink.mdw.dataaccess.DatabaseAccess.<init>(DatabaseAccess.java:142)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at com.centurylink.mdw.hub.MdwMain.startup(MdwMain.java:76)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at com.centurylink.mdw.hub.StartupListener.contextInitialized(StartupListener.java:40)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:976)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-12-08T12:31:59.96-0700 [App/0]      OUT    at java.lang.Thread.run(Thread.java:745)
2017-12-08T12:32:00.12-0700 [App/0]      OUT [(i)20171208.19:32:00.128 ~13] Compiling Dynamic Java class: com.centurylink.mdw.db.MariaDBEmbeddedDb
```

**Comment by jbrojdeCTL** [comment]
What is the reason why .cfignore should not also ignore the .git directory?   If .git was ignored during cf push, would those pushed assets be replaced during startup when MDW clones repo?

**Comment by donaldoakes** [comment]
That's exactly the point of this issue.  We want to be able to ignore .git.  Currently if we ignore .git and keep `mdw.git.local.path` as ".", then we get the stack trace in the first comment above.  If we change `mdw.git.local.path` to something other than ".", then that problem is fixed, but then whatever assets are being pushed in local are ignored and only imported assets can be used.  This works fine for non-dev purposes, but it effectively prevents you from trying out changes via `cf push` without committing them to Git.  We need to enhance mdw-buildpack to handle non-"." locations because it's currently wired to push relative to the project directory (".").
